### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by rawiasammout** [paudan/scikit-roughsets#1]
Hi i can't install the package any help please 

i will be appreciated.

**Comment by paudan** [comment]
Hi, I have not pushed it to PyPi (at least yet), but you can simply install directly from GitHub:
 ```bash
pip install git+https://github.com/paudan/scikit-roughsets.git
```
It worked fine for me under both Linux and Win.

**Comment by rawiasammout** [comment]
yes thanks a lot Paudan. 
Waiting an example to understand exactely your code 

Thanks for your feedback
